# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0.xci
# IP: The module: 'game_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0.xci
# IP: The module: 'game_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/uzahid/workspace/billiard_game/vivado/billiard_game/billiard_game.srcs/sources_1/bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
