# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/uzahid/workspace/billiard_game/vivado/constraints/game.xdc

# Block Designs: bd/game/game.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==game || ORIG_REF_NAME==game} -quiet] -quiet

# IP: bd/game/ip/game_game_top_0_0/game_game_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==game_game_top_0_0 || ORIG_REF_NAME==game_game_top_0_0} -quiet] -quiet

# IP: bd/game/ip/game_clk_wiz_0_0/game_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==game_clk_wiz_0_0 || ORIG_REF_NAME==game_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/game/game_ooc.xdc
